version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
        POSTGRES_DB: kraken_db
    networks:
        - kraken
networks:
  kraken:
